### ISSUE TITLE
Investigation: User reported error when submitting reportbacks

### ISSUE THREAD

**Issue by ngjo** [DoSomething/phoenix-next#1268] opened 2019-02-21 16:38 UTC
### Current Behavior
[Greg first flagged on Slack](https://dosomething.slack.com/archives/C2BLZGBPH/p1549572815004700) that users were having issues reporting back across multiple campaigns, but specifically Treat Yo Friends & Not So Secret Admirer.

Greg reports that "90% of the emails I get reference a "Something went wrong" message, but when I propose they reload the browser, they act like they hadn't considered that. So, this may be 1 of 2 different "something went wrong" messages." He [guesses](https://dosomething.slack.com/archives/C2BPA7M8F/p1550772360028900?thread_ts=1550761077.023100&cid=C2BPA7M8F) that he's gotten ~25 emails regarding this issue.

![image 22](https://user-images.githubusercontent.com/2658867/53186417-f61ad700-35ce-11e9-959a-7e5d6dfcfdfd.png)

We [received](https://dosomethingorg1.zendesk.com/agent/tickets/313388) one of these screenshots that has the timestamp "Screen Shot 2019-02-15 at 7.54.49 PM.png" and the user reported they were on Safari.

### Expected Behavior
Users can report back or receive an error message that is useful and helps them successfully report back .

#### Additional Information

- We haven't seen any issues in Ghost Inspector, but right now it's [scheduled](https://app.ghostinspector.com/suites/565c775f3248e5e72835194d/edit#schedule) to run once a day during the week
- One theory was that this could be an image size issue, but it seems to not be the culprit as (1) they wouldn't get the "something went wrong" error, instead they should get an error about their image being too big and (2) [according to Papertrail](https://papertrailapp.com/systems/dosomething-phoenix/events?q=Exception%20from%20%22POST%20v3%2Fposts%22%3A&focus=1035098838111371268), between Feb 16 & Feb 21, it looks like there were only ~60 image size errors.
- After digging into it a bit more on Feb 11, the [only error that stood out in New Relic ](https://goo.gl/shBsXA
)was this one -- however, there were only 23 occurrences in the week prior to Feb 11: ```Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.```
- When Mendel & Greg synced IRL, Greg mentioned that at least some issues were resolved by users refreshing or switching browsers, which is a pretty strong indicator that some could be due to the token auth issue -- [a Pivotal ticket was made for that work](https://www.pivotaltracker.com/n/projects/2019313/stories/157665698). 
- Mendel used Keen [to determine](https://keen.io/projects/59c27379c9e77c000109614e/explorer?query%5Bevent_collection%5D=phoenix_failed_photo_submission_action&query%5Banalysis_type%5D=count_unique&query%5Btarget_property%5D=user.northstarId&query%5Btimezone%5D=US%2FEastern&query%5Bfilters%5D%5B0%5D%5Bproperty_name%5D=data.error.response.error.code&query%5Bfilters%5D%5B0%5D%5Boperator%5D=eq&query%5Bfilters%5D%5B0%5D%5Bproperty_value%5D=500&query%5Btimeframe%5D=this_30_days) that ~500 people in the last 30 days had a `phoenix_failed_photo_submission_action` error (relates to when a report back fails to go through our system).

#### Next Steps
Here are some potential next steps that we can take once we determine priority against other work.

- [ ] Understand scope more from other campaign leads
- [ ] ~Possibly increase Ghost Inspector or other monitoring to try to catch this "something went wrong" error~ (see comment)
- [ ] [Tackle the token auth issue](https://www.pivotaltracker.com/n/projects/2019313/stories/157665698)

**Comment by ngjo** [comment] 2019-02-21 20:07
Looks like the specific Ghost Inspector tests for campaign signup to reportback [runs hourly](https://app.ghostinspector.com/tests/5c4a1efd638e692a23208132) and it hasn't caught this issue. One thing that supports Mendel's through re:token auth issue is that this Ghost Inspector test goes through the steps of someone creates a new account and immediately reports back.

**Comment by mendelB** [comment] 2019-02-21 20:21
@ngjo On New Relic, over the past 7 days, we can see a sizable amount of `Gateway\Server\Exceptions\AccessDeniedException` errors (the error that would be thrown for a authentication token issue) filtered down to the place within Phoenix where we'd be processing RB posts. 

https://rpm.newrelic.com/accounts/108038/applications/131065162/filterable_errors#/table?top_facet=transactionUiName&primary_facet=transactionName&barchart=barchart&filters=%5B%7B%22key%22%3A%22error.class%22%2C%22value%22%3A%22DoSomething%5C%5CGateway%5C%5CServer%5C%5CExceptions%5C%5CAccessDeniedException%22%2C%22like%22%3Afalse%7D%2C%7B%22key%22%3A%22transactionName%22%2C%22value%22%3A%22WebTransaction%2FAction%2FApp%5C%5CHttp%5C%5CControllers%5C%5CApi%5C%5CCampaignPostsController%40store%22%2C%22like%22%3Afalse%7D%5D

**Comment by ngjo** [comment] 2019-02-21 20:24
@mendelB thanks! I don't have a New Relic account -- could you quantify "sizable" here?

**Comment by mendelB** [comment] 2019-02-21 20:31
Ah sorry! The exact number is 1459 for the past 7 days (the maximum timespan we can search back through)

**Comment by ngjo** [comment] 2019-02-21 23:02
Seems like we have two errors going on -- the one above and then this one (I blocked out their faces):

<img width="875" alt="screen shot 2019-02-21 at 4 30 28 pm" src="https://user-images.githubusercontent.com/2658867/53207476-ca651480-3601-11e9-9f0d-46dbd8cd22ef.png">

We received their message at Thu, Feb 21, 2019 at 4:36 PM  and they said "I tried using multiple formats (PNG, JPEG, etc.)" 

[Confirmed in Rogue](https://activity.dosomething.org/signups/10129117) that this user's RB didn't go through.

**Comment by ngjo** [comment] 2019-02-21 23:04
Innnnterestingly, I tried reporting back on QA (different campaign tho) w/ all of the content they provided and I got stopped w/ a specific caption length issue:

![screen shot 2019-02-21 at 6 01 06 pm](https://user-images.githubusercontent.com/2658867/53207876-f3d27000-3602-11e9-989f-867095315ecd.png)

[When I cut the caption down it could go through...](https://activity-qa.dosomething.org/signups/10151795)

**Comment by mendelB** [comment] 2019-02-21 23:11
Hmm I can confirm that I got the same message as that user on a page I'd kept open for a while:
![image](https://user-images.githubusercontent.com/12417657/53208233-04cfb100-3604-11e9-9757-139a8976c13d.png)


I double checked my local user auth token and it's indeed expired.

**Comment by mendelB** [comment] 2019-02-21 23:13
(It's possible that that user never got to see the caption validation error, since their request failed authentication first)

**Comment by DFurnes** [comment] 2019-02-22 15:50
This "something went wrong" error is from our [error boundry](https://reactjs.org/docs/error-boundaries.html), which is displayed when there is a fatal error rendering part of the page (which would otherwise have caused the entire page to crash):

![screen shot 2019-02-22 at 10 37 33 am](https://user-images.githubusercontent.com/583202/53252852-e1514880-368d-11e9-90cf-6432572ab941.png)

If a photo/text submission results in a server-side error, it'll be displayed like this:

<img width="588" alt="screen shot 2019-02-21 at 5 42 18 pm" src="https://user-images.githubusercontent.com/583202/53252872-eadab080-368d-11e9-9eaf-b516ef7cffbb.png">

Expired authentication token errors fall within the second bucket. These should absolutely be cleared up by refreshing the page – they happen because [access tokens](https://github.com/DoSomething/northstar/blob/master/documentation/authentication.md#access-tokens) are valid for one hour, but folks can leave a browser tab open for longer than that.

**Comment by DFurnes** [comment] 2019-02-22 16:51
To help put the token errors in context, here's an area graph of successful requests (blue) versus token errors (yellow) to Phoenix's `CampaignPostsController` over the past week ([New Relic Insights query](https://insights.newrelic.com/accounts/108038/query?hello=overview&query=SELECT%20count(*)%20from%20Transaction%20FACET%20cases(WHERE%20errorMessage%20LIKE%20%27%25AccessDenied%25%27%20AS%20token_errors,%20WHERE%20httpResponseCode%20%3D%20500%20as%20other_errors,%20WHERE%20httpResponseCode%20%3D%20201%20AS%20successes)%20WHERE%20appName%20%3D%20%27dosomething-phoenix%27%20and%20name%20%3D%20%27WebTransaction%2FAction%2FApp%5C%5CHttp%5C%5CControllers%5C%5CApi%5C%5CCampaignPostsController@store%27%20SINCE%201%20week%20ago%20TIMESERIES%20auto)):

![screen shot 2019-02-22 at 11 41 18 am](https://user-images.githubusercontent.com/583202/53256814-cafbba80-3696-11e9-896e-b0e481e7a501.png)

What we _can't_ easily see (here) is how many of these requests are solved when folks simply refresh their browser and try again (since one person spamming the "Submit" button could inflate these errors, even if we still get their one reportback after they refresh the page and submit successfully).

**Comment by DFurnes** [comment] 2019-02-22 16:54
@mendelB Can we use that Puck query to see how many unique users had a `phoenix_failed_photo_submission_action` without a corresponding `phoenix_submitted_photo_submission_action` for the same campaign?

**Comment by weerd** [comment] 2019-02-22 17:03
> Innnnterestingly, I tried reporting back on QA (different campaign tho) w/ all of the content they provided and I got stopped w/ a specific caption length issue:

@ngjo, likely the user would have been stopped as well regarding the caption, if the OAuth error didn't stop them first.

**Comment by ngjo** [comment] 2019-02-22 17:09
> [access tokens](https://github.com/DoSomething/northstar/blob/master/documentation/authentication.md#access-tokens) are valid for one hour

@DFurnes is this a recommended length or did we just set it at this to start? I.e., are there upper bounds to how long we'd want to keep them valid?

**Comment by mendelB** [comment] 2019-02-22 17:18
> @mendelB Can we use that Puck query to see how many unique users had a `phoenix_failed_photo_submission_action` without a corresponding `phoenix_submitted_photo_submission_action` for the same campaign?

Keen funnel coming in hot! For the Not-So-Secret-Admirer campaign, for the past 30 days, of the 339 users who received a `phoenix_failed_photo_submission_action` event with a `500` error code, 225 subsequently received the `phoenix_completed_photo_submission_action` event.

https://goo.gl/mWM9W8

**Comment by DFurnes** [comment] 2019-02-22 17:18
> @DFurnes is this a recommended length or did we just set it at this to start? I.e., are there upper bounds to how long we'd want to keep them valid?

This was the [suggested default](https://oauth2.thephpleague.com/authorization-server/auth-code-grant/) from the OAuth server package we use. Ideally, we'd want that length to be even shorter (like Laravel Passport, which [sets a  10 minute expiry](https://github.com/laravel/passport/blob/670a358d15e4320bd5d2ddb0253ec65344df4a3c/src/PassportServiceProvider.php#L152)) since tokens are stateless & so the only way to "invalidate" an existing token is to wait for it to expire.

**Comment by weerd** [comment] 2019-02-22 17:20
@DFurnes @ngjo Do we maybe want to discuss bumping this ticket up? https://www.pivotaltracker.com/story/show/157665698

**Comment by DFurnes** [comment] 2019-02-22 17:32
> Keen funnel coming in hot! For the Not-So-Secret-Admirer campaign, for the past 30 days, of the 339 users who received a `phoenix_failed_photo_submission_action` event with a `500` error code, 225 subsequently received the `phoenix_completed_photo_submission_action` event.

So if I'm understanding correctly, that means 114 unique users did _not_ submit a post for this campaign due to having an expired access token (which is 8% of the total "successful" submissions over that time period). That definitely sounds like a good argument for bumping the priority of that ticket. 👍

**Comment by mendelB** [comment] 2019-02-22 17:42
Yeah that's def my understanding as well! ➕

**Comment by ngjo** [comment] 2019-02-22 18:15
Thinking through prioritization against other work (prom) - just wanted to confirm two things:

1. The Pivotal is marked as a 3 -- that still holds true?
2. This would be Phoenix work and therefore most likely a Rocket person would be best suited to tackle it most efficiently?

**Comment by DFurnes** [comment] 2019-02-22 20:06
Yep, 3 or 5. And yep. 👍 I've also been investigating a deeper refactoring of how we handle auth on the web, which I'll make a write-up on soon (but wouldn't in any way block a quick fix here).

**Comment by DFurnes** [comment] 2019-02-27 18:54
Just to close the loop, I've applied that "quick fix" to this in #1276 and it's been deployed! I'll keep an eye on metrics over the next week and post here with an update once the dust settles.

**Comment by weerd** [comment] 2019-03-05 19:15
@DFurnes does it look like we can close this ticket now that your fix has been applied?

**Comment by DFurnes** [comment] 2019-03-05 21:52
@weerd Yep, I just wanted to wait until we had collected enough metrics to ensure this fix had actually cleared up the problem. Luckily, it looks like that's the case!

Compared to [last week](
https://github.com/DoSomething/phoenix-next/issues/1268#issuecomment-466465233), we've cut our token error rate down so much that it barely shows on the graph:

![screen shot 2019-03-05 at 4 47 25 pm](https://user-images.githubusercontent.com/583202/53839885-ab9e4080-3f66-11e9-906e-972e6c68554a.png)

Going to close this out & cross-post to the Pivotal card for this work as well.

**Closed by DFurnes** 2019-03-05 21:52 UTC
